### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by Ciget** [safakgur/guard#1]
Hi,

do you have any plan to release stable version?

**Comment by safakgur** [comment]
Hi, I'm sorry that I missed the notification for this issue. I've been really busy for the last couple of months, I guess I clicked that "Mark all as read" button too many times.

Yes, I'm going to release 1.0 when the unit tests are completed but it may take one more month or so. In the meantime, I'm open to pull requests that implement the placeholder unit tests.
