### ISSUE TITLE
Interface limitations

### ISSUE THREAD

**Issue by dariusbuinovskij** [safakgur/guard#14]
Hi,

Interfaces have limited support when you would like to set validation results. It works OK with value types and classes.
Are you planning to fix that?
`	interface IMyTestInterface
	{}`

`class MyTestClass
	{
		IMyTestInterface cvalue;
		MyTestClass(IMyTestInterface value)
		{
   cvalue = Guard.Argument(() => value).NotNull();
		}
	}`

If you will copy and try to compile code I added before you will get following error:

**Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'Dawn.Guard.ArgumentInfo<ConsoleApp6.IMyTestInterface>' to 'ConsoleApp6.IMyTestInterface'**

I can fix that by writing ".Value" like that, but I would like to avoid that (same as for other objects):
`cvalue = Guard.Argument(() => value).NotNull().Value;`

**Comment by safakgur** [comment]
Unfortunately, it is not possible since the C# spec disallows user-defined conversions from and to interfaces.

See [this section][1] in the specification:

> For a given source type S and target type T, if S or T are nullable types, let S0 and T0 refer to their underlying types, otherwise S0 and T0 are equal to S and T respectively. A class or struct is permitted to declare a conversion from a source type S to a target type T only if all of the following are true:
>
> S0 and T0 are different types.
> Either S0 or T0 is the class or struct type in which the operator declaration takes place.
> **Neither S0 nor T0 is an interface_type.**
> Excluding user-defined conversions, a conversion does not exist from S to T or from T to S.

[1]: https://github.com/dotnet/csharplang/blob/master/spec/conversions.md#permitted-user-defined-conversions "Permitted user-defined conversions"

**Comment by dariusbuinovskij** [comment]
Yes, now I see the reason and don't see any good solutions for that. Library still looks good and will continue testing.
Thanks for a quick response.

**Comment by safakgur** [comment]
Thank you for using Guard.

I'm closing the issue as currently, there is no way around this limitation.

**Comment by Ammonius** [comment]
You can easily add an extension method to convert an ArgumentInfo to an interface type, so you can keep the single-line convenience:

```
    public static class GuardArgumentInfoInterfaceConverter
    {
        public static T GetInterface<T>(in this Guard.ArgumentInfo<T> o)
        {
            return (T)o.Value;
        }

    }

```
