### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by JamesReate** [safakgur/guard#31]
Is there a reason this library does not have a nuget package?

**Comment by JamesReate** [comment]
After searching for a while in nuget, I found that there IS a package...
Anyhow, it would be useful that the readme.md have the nuget installation command or link to nuget package. Thanks for great library!

**Comment by safakgur** [comment]
Hi James, I'm glad you liked the library. The following button should take you to the package page.

![image](https://user-images.githubusercontent.com/1020499/61271303-e3d34c80-a7ac-11e9-9692-b13b83a779ac.png)

Do you think it would be more clear if we add `PM> Install-Package Dawn.Guard` to the introduction?

**Comment by JamesReate** [comment]
I don't know how I didn't see that 🤷‍♂ 
I think it would be helpful to add the command line in the intro as well- makes it quick to copy paste and harder to miss. My opinion though would be to use the CLI ie. `dotnet add package Dawn.Guard`

**Comment by safakgur** [comment]
Added in 68e2bc608327abdfaa50337cc063171407b85905. Thank you for the suggestion.
