### ISSUE TITLE
Relevant namespace should be easy to find

### ISSUE THREAD

**Issue by ltouro** [safakgur/guard#35]
I had to browse the source-code to find the namespace that I should import is "Dawn".

Guess that should be added somewhere in the README to easy the onboarding.

**Comment by safakgur** [comment]
Good point, I thought the package name being Dawn.Guard would signal the namespace but you are right as it wasn't explicit enough. I added the namespace to the first example in readme with f8da6d182262e33d9e2b09daab73e2da0bced3e8.

Thank you for the recommendation.
