### ISSUE TITLE
Interop NotNullWhenAttribute leaks

### ISSUE THREAD

**Issue by leecannon** [safakgur/guard#44]
The implementation of NotNullWhenAttribute included for interop purposes [here](https://github.com/safakgur/guard/blob/a6951af78b4337fd96d095bcdd09d913dac3ec19/src/Guard.Interop.cs#L159) (entire relevant section copied below) leaks.

I also have a library that uses a copy of the implementation of NotNullWhenAttribute to target new and old frameworks while allowing code to use NotNullWhen, due to this trying to reference Dawn.Guard results in a duplicate declaration error.

My library marks the implementation of NotNullWhenAttribute as internal preventing any leaking however as Dawn.Guards implementation is public this results in duplicate declaration.

Can your version be marked internal?

``` cs
#if NETSTANDARD1_0 || NETSTANDARD2_0
namespace System.Diagnostics.CodeAnalysis
{
    /// <summary>Required for reference nullability annotations.</summary>
    [AttributeUsage(AttributeTargets.Parameter, Inherited = false)]
    public sealed class NotNullWhenAttribute : Attribute
    {
        /// <summary>Initializes a new instance of the <see cref="NotNullWhenAttribute" /> class.</summary>
        /// <param name="returnValue">If the method returns this value, the associated parameter will not be null.</param>
        public NotNullWhenAttribute(bool returnValue) => this.ReturnValue = returnValue;

        /// <summary>Gets the return value condition.</summary>
        public bool ReturnValue { get; }
    }
}
#endif
```

**Comment by safakgur** [comment]
Thank you for letting me know - I made it internal with 7080fcad4dffc5e07b3f166e869ebe8cf111ed2a and will push a release this week.
