### ISSUE TITLE
Problem with "InitContainsDuplicate" on .NET < 4.7.2

### ISSUE THREAD

**Issue by dr1zzle** [safakgur/guard#48]
Hello,

first of all, I wan't to thank you for providing this nice library.
I'm currently trying to use it within a project that uses a rather old .NET version (4.5.2) and the following problem emerged:

**To Reproduce**
.NET Framework version < 4.7.2 on target machine.
Using any of the `Guard.Collection<T>` methods.

**Expected behavior**
No runtime exceptions during initialization.

**Actual behavior**
Throws an argument null exception at [this line of code](https://github.com/safakgur/guard/blob/96e4532883285c8d94bf3fc80bf3248573b29048/src/Guard.IEnumerable.cs#L1053).

I did a little bit of research and found this: Prior to version 4.7.2 `HashSet<T>` ([documentation](https://docs.microsoft.com/en-gb/dotnet/api/system.collections.generic.hashset-1.-ctor?view=netframework-4.7.1)) does not appear to have constructor that takes an integer argument (in other words the initial capacity of the `HashSet<T>`).

As I'm probably one of a very few devs to experience this kind of error I'm not sure how you want to proceed with this issue.

**Comment by safakgur** [comment]
Hi there,

Kudos for tracking this bug to the line! net45 and above are still supported, so I'll be fixing this shortly.

Automated testing of multiple platforms was a real pain and I unfortunately had to [let it go](https://github.com/safakgur/guard/commit/ce311ce3a9378c3c2c59179f19a6eb32152342c8). Now that v2 is close, I think I'll give it another go.

Thanks for using the library.
