### ISSUE TITLE
Multiple checks with same custom message

### ISSUE THREAD

**Issue by anas2204** [safakgur/guard#49]
If I want to check both NotNull() and NotEmpty() with the same error message just written once, can this be done?
I'm referring to [this](https://github.com/safakgur/guard/blob/dev/docs/design-decisions.md#exception-messages) way of putting in messages, but not put for each one again and again.

**Comment by safakgur** [comment]
Unfortunately not, messages are validation-specific. Though I recommend using different messages in any case as it would be more helpful from the catcher's perspective.

Is there a particular reason you don't prefer the default messages?

**Comment by anas2204** [comment]
No specific reason, sometimes custom messages are easier to debug, but I understand the design and not an issue!
Thanks

**Comment by safakgur** [comment]
Understood, closing the issue then. Thank you for using Guard.
