### ISSUE TITLE
How to Guard an ICollection member

### ISSUE THREAD

**Issue by anas2204** [safakgur/guard#50]
If I have a `class Student` which has an `ICollection<Class> Classes {get; set; }`, I'm trying to do this.

```
Guard.Arguement(() => student)
.NotNull()
.Member(student.Classes , classes => classes.NotEmpty());
```

But the **classes** variable isn't an `ICollection<Class>` but `Guard.ArgumentInfo<ICollection<Class>>` so the NotEmpty() check isn't available on Intellisense.
The Visual Studio Intellisense doesn't auto-suggest the available methods for a collection, but it does compile and work.

Autosuggest works fine here though:
`Guard.Arugment(() => student.Classes)).NotEmpty();`

Following the examples [here ](https://github.com/safakgur/guard/blob/dev/docs/design-decisions.md#validating-argument-members)

Is this known?

**Comment by safakgur** [comment]
Just tested, you are right:

```c#
// Auto-complete for NotEmpty works.
Guard.Argument(() => classes).NotEmpty());

// Auto-complete for NotEmpty does not work.
Guard.Argument(() => student).Member(s => s.Classes, c => c.NotEmpty());
```

> Is this known?

Nope, this is a new one for me. It seems like an IntelliSense bug (it happens on Visual Studio 2019 and Visual Studio Code, but not on Rider), so I doubt there is anything we can do except maybe filing a bug for Visual Studio/Code?

In any case - thank you letting me know!
