### ISSUE TITLE
CA1062 warning

### ISSUE THREAD

**Issue by BartNetJS** [safakgur/guard#52]
How can I avoid CA1062 warnings when using for example
Guard.Argument(message, nameof(message)).NotNull();

I tried the following in .editorconfig in visual studio 2019 solution root:
dotnet_code_quality.CA1062.null_check_validation_methods = Guard.NotNull
dotnet_code_quality.CA1062.null_check_validation_methods = Guard.Argument

**Comment by ShyKneeOne** [comment]
I had luck with
dotnet_code_quality.CA1062.null_check_validation_methods = M:Dawn.Guard.Argument`1(`).NotNull
However, it only seemed to work when defined in a .editorconfig at the project root.  I believe the settings are inherited so you may only need a single line in the project level .editorconfig

**Comment by 4nandP** [comment]
I'm also on the hunt for a guard library that will allow me to satisfy CA1062 without having to turn it off. This may help but like above I haven't found the correct combo to use
https://github.com/mavasani/roslyn-analyzers/blob/970a5c94412c05eaef331a42d83b5db6da736365/docs/Analyzer%20Configuration.md#null-check-validation-methods

**Comment by 4nandP** [comment]
LiteGuard works out of the box

**Comment by red55** [comment]
@BartNetJS  just use full qualified name of method in .editor config
```dotnet_code_quality.CA1062.null_check_validation_method = Dawn.Guard.Argument.NotNull```
> dotnet_code_quality.CA1062.null_check_validation_methods = Guard.NotNull
> dotnet_code_quality.CA1062.null_check_validation_methods = Guard.Argument

@safakgur It would be great if there is a away to make Dawn.Guard work with Rosalyn based analyzers out of the box.

**Comment by red55** [comment]
> I'm also on the hunt for a guard library that will allow me to satisfy CA1062 without having to turn it off. This may help but like above I haven't found the correct combo to use
> https://github.com/mavasani/roslyn-analyzers/blob/970a5c94412c05eaef331a42d83b5db6da736365/docs/Analyzer%20Configuration.md#null-check-validation-methods

Try this one https://github.com/danielwertheim/Ensure.That/tree/master/src/projects/EnsureThat
```Ensure.That().IsNotNull()``` is not compliant with CA1062, but ```EnsureArg.IsNotNull()``` works fine.

**Comment by WizX20** [comment]
I think this is related: [CA1062 editorconfig issue with null_check_validation_methods in other project in solution](https://github.com/dotnet/roslyn-analyzers/issues/3451)

**Comment by safakgur** [comment]
Hi folks, fixing NRT issues was on the roadmap for v2 but unfortunately, I'm retiring Guard - I apologise for any inconvenience, and thank you for all the support. The readme has details.
