### ISSUE TITLE
Support validation/guard-clauses for collection items

### ISSUE THREAD

**Issue by penenkel** [safakgur/guard#53]
I could not find a way to specify constraints for items in a collection. Did I overlook something? This seems to me like a fairly common scenario, or is it not?

**Scenario**
A collection of items `List<SomeItem> collection;`

Each item has a property
```
class SomeItem{
   public object SomeProperty {get; set;}
}
```
I wish to assert that (1) the collection is not null and that for each item within the collection that (2) it is not null and that (3) the property is not null.

**Feature**
I envision something like the following syntax:
```
Guard.Argument(collection, nameof(collection))
  .NotNull()
  // specify nested constraints that are applied to each item in the collection
  .Item(x=> x
    .NotNull()
    .Member(item => item.SomeProperty, x => x.NotNull())
  );
```

**Comment by safakgur** [comment]
Hi @penenkel, this looks like a great future request, but unfortunately, I'm retiring Guard - I apologise for any inconvenience, and thank you for all the support. The readme has details.
