### ISSUE TITLE
Guard variants for nullable types

### ISSUE THREAD

**Issue by dominikjeske** [safakgur/guard#54]
I'm testing library in c# 8 environment. It looks good but I have warning where using nullables variants of standard types. For example when I'm trying this code:

```
public static string Test(string? text)
{
    text = Guard.Argument(() => text).NotNull();
    return text.Substring(0, 1);
}

```
I have two warnings:

Warning	CS8634	The type 'string?' cannot be used as type parameter 'T' in the generic type or method 'Guard.NotNull<T>(in Guard.ArgumentInfo<T>, string?)'. Nullability of type argument 'string?' doesn't match 'class' constraint
Warning	CS8619	Nullability of reference types in value of type 'Guard.ArgumentInfo<string?>' doesn't match target type 'Guard.ArgumentInfo<string>'

I think that string? and others need additional care?

**Comment by drewburlingame** [comment]
I ended up adding an extension method for the `string?` case which was common for us.

```c#

    /// <summary>Requires the argument to be null</summary>
    /// <remarks>Added so the null ref warning only occurs in one file and can be easily ignored.</remarks>
    [DebuggerStepThrough]
    public static ref readonly Guard.ArgumentInfo<string> NotNullString(
        in this Guard.ArgumentInfo<string?> argument) =>
#pragma warning disable CS8634
        ref argument.NotNull()!;
#pragma warning restore CS8634
```

**Comment by safakgur** [comment]
Hi folks, the intended usage was to accept a non-nullable string given that marking it as nullable would signal callers that it's ok to pass null where in reality we throw when it is null. With that said, I'm retiring Guard - I apologise for any inconvenience, and thank you for all the support. The readme has details.
