### ISSUE TITLE
Binary Backward Compatibility

### ISSUE THREAD

**Issue by nathanaw** [safakgur/guard#60]
Version 1.4.0 introduced a binary breaking change to the library due to the addition of new optional parameters to constructor on the ArgumentInfo struct. Similar changes occurred on other methods in versions up through version 1.6.0.

See this report for a summary of the changes from 1.3.0 to 1.4.0:
https://www.fuget.org/packages/Dawn.Guard/1.4.0/lib/netstandard2.0/diff/1.3.0/

The addition of optional parameters causes binary runtime incompatibilities between versions. This can cause problems when a project uses multiple libraries that were compiled against different versions of the Dawn package.

**To Reproduce**
See this git repo: https://github.com/nathanaw/dawn-guard-binary-compat 

**Expected behavior**
Semantic versioning would have all versions that share a major version number be backwards compatible.

**Actual behavior**
A MissingMethodException is thrown when code compiled against a pre 1.4.0 version runs in a process that loaded the 1.4.0 or later.

**Purpose of Report**
While it is likely not feasible or advisable to revise prior versions, this bug report aims to highlight the impact of adding optional parameters. Future releases might consider using method overloads to add additional parameters as a means to maintain backwards compatibility.

It appears that version 1.6.0 through 1.12.0 are binary backwards compatible. There are no removals. Only additions. 👍 
https://www.fuget.org/packages/Dawn.Guard/1.12.0/lib/netstandard2.0/diff/1.6.0/

**Praise**
I am a big fan of the Dawn.Guards package. The design and implementation are impressive and highly useful for my projects. Many thanks to the contributors.

**Comment by safakgur** [comment]
Thanks a lot for raising this @nathanaw and I apologise for any headaches I must've caused!

The bad news is, the upcoming v2 includes a lot of breaking changes (it is a major version bump, but still).

The good news is, no more boolean flags! We now use method overloads and on some instances, flag enums (with a promise to never change the existing flags without a major version bump).

Binary compatibility is easier to miss than source compatibility, but I'll be much more careful from now on, thanks again!

**Comment by nathanaw** [comment]
Thanks @safakgur!

Looking forward to v2 and the features you're adding too. 👍
