### ISSUE TITLE
Document inclusivity of InRange

### ISSUE THREAD

**Issue by kjkrum** [safakgur/guard#61]
It would be nice if the doc comments for `InRange` mentioned inclusivity. Without reading the code, it seems ambiguous to me whether it works like SQL `between` (min <= x <= max) or the way limits are often expressed with zero-based counters (min <= x < max).

**Comment by safakgur** [comment]
I see your point. The argument docs imply inclusivity by stating the value represents "...min/max value the argument is **allowed to have**", but yeah I guess it wouldn't hurt to be more explicit in the summary as well. Thanks for the suggestion!

<img width="540" alt="Screenshot 2021-12-27 at 15 05 36" src="https://user-images.githubusercontent.com/1020499/147483969-27b3a9bb-0bd6-44ac-afd0-3a637cab1e8f.png">

**Comment by safakgur** [comment]
Hi @kjkrum, I'm retiring Guard - I apologise for any inconvenience, and thank you for all the support. The readme has details.
