### ISSUE TITLE
'NotNull' validation should be available for unconstrained generic types

### ISSUE THREAD

**Issue by julealgon** [safakgur/guard#64]
**Is your feature request related to a problem?**
I realized today that the library doesn't currently expose a `NotNull` validation when validating arguments of unconstrained generic types. This results in cumbersome validation for null when null doesn't make sense for the implementation when T happens to be a reference type.

Since the consumer doesn't actually know whether or not the generic type is a `struct` or a `class`, we have to validate the value in a way that works for both, and checking for `null` directly is not only a good solution, but even [recommended](https://stackoverflow.com/a/5340850/1946412).

Forcing a `class` constraint on the consumer changes the behavior and is not always a good solution (it is quite common for an implementation to work just fine regardless if T is a value or a reference type, as long as _it is not null when it is a reference type_.

**Describe the solution you'd like**
`NotNull` should be available when doing `Guard.Argument<T>(T)` and implemented the same way a normal null comparison is.

**Comment by julealgon** [comment]
PS: I'm currently working around this limitation with the less-than-ideal alternative:
```csharp
Guard.Argument(arg).Require<ArgumentNullException>(static value => value is not null);
```

**Comment by safakgur** [comment]
Hi folks, I'm retiring Guard - I apologise for any inconvenience, and thank you for all the support. The readme has details.
