### ISSUE TITLE
Linux and macOS builds

### ISSUE THREAD

**Issue by safakgur** [safakgur/guard#8]
Generic xUnit theories don't initialize on some non-Windows platforms. They work on AppVeyor's Ubuntu image but fail on Travis' Trusty and macOS images. They also fail on WSL-Ubuntu 16.04.4.

Reverting a previous version of xUnit may help. An option is to convert our generic tests to non-generic ones and another is to keep Travis builds disabled until the xUnit folks release a fix.

Here are the issues on their side:
* https://github.com/xunit/xunit/issues/1781
* https://github.com/xunit/xunit/issues/1788

**Comment by ViktorHofer** [comment]
Will be fixed with https://github.com/xunit/xunit/pull/1790

**Comment by safakgur** [comment]
Great! Just tried a [Travis build][1] on macOS using [xUnit 2.4.1-alpha.1.build4054][2] - worked like a charm. I'll update the dependency on `dev` as soon as it hits stable.

[1]: https://travis-ci.org/safakgur/guard/builds/418725424
[2]: https://myget.org/feed/xunit/package/nuget/xunit/2.4.1-alpha.1.build4054

**Comment by ViktorHofer** [comment]
Happy to hear :) There are 1-2 other bugs in 2.4 related to generics, but if you don't hit them everything's fine!

**Comment by safakgur** [comment]
Re-enabled Travis builds with 1b64baed2f061f1e5f8b52812ae0451d14129787.
